# Generated by Django 3.2.4 on 2021-06-26 13:38

import Chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0008_alter_chattyuser_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChattyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('group_image', models.ImageField(blank=True, upload_to=Chat.models.group_image_pathname)),
                ('group_description', models.TextField(blank=True, null=True)),
                ('date_created', models.BigIntegerField()),
                ('secret_key_admin', models.CharField(blank=True, default='', max_length=50)),
                ('secret_key_join', models.CharField(blank=True, default='', max_length=50)),
                ('is_dialogue', models.BooleanField()),
                ('group_admin', models.ManyToManyField(blank=True, related_name='admin', to='Authentication.ChattyUser')),
                ('group_members', models.ManyToManyField(related_name='members', to='Authentication.ChattyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Text', 'Text'), ('Pure Text', 'Pure Text'), ('Image with Caption', 'Image with Caption'), ('File with Caption', 'File with Caption'), ('Text with Refferal', 'Text with Refferal'), ('Image with Refferal', 'Image with Refferal'), ('File with Refferal', 'File with Refferal')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Chat.models.message_image_pathname)),
                ('other_file', models.FileField(blank=True, null=True, upload_to=Chat.models.message_file_pathname)),
                ('date_created', models.BigIntegerField()),
                ('date_received', models.BigIntegerField(blank=True, null=True)),
                ('pinned', models.BooleanField()),
                ('message', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.chattygroup')),
                ('message_refer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_to', to='Chat.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.chattyuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChattyUserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieve_group_notification', models.BooleanField(default=True)),
                ('recieve_chat_notification', models.BooleanField(default=True)),
                ('counter', models.BooleanField(default=True)),
                ('see_phone_number', models.CharField(choices=[('everybody', 'Everybody'), ('acquaintance', 'Acquaintance'), ('nobody', 'Nobody')], default='acquaintance', max_length=30)),
                ('see_description', models.CharField(choices=[('everybody', 'Everybody'), ('acquaintance', 'Acquaintance'), ('nobody', 'Nobody')], default='everybody', max_length=30)),
                ('see_last_seen', models.CharField(choices=[('everybody', 'Everybody'), ('acquaintance', 'Acquaintance'), ('nobody', 'Nobody')], default='everybody', max_length=30)),
                ('see_profile_photo', models.CharField(choices=[('everybody', 'Everybody'), ('acquaintance', 'Acquaintance'), ('nobody', 'Nobody')], default='everybody', max_length=30)),
                ('secretKeyCode', models.CharField(blank=True, max_length=100)),
                ('site_text_color', models.CharField(default='#000000', max_length=50)),
                ('site_background_color', models.CharField(default='#f4f4f4', max_length=50)),
                ('chat_message_color', models.CharField(default='#484aeb', max_length=50)),
                ('send_by_enter', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_users', to='Authentication.ChattyUser')),
                ('chatty_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatty_user_set', to='Authentication.chattyuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChattyUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date_sent', models.BigIntegerField()),
                ('chatty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatty_user_not', to='Authentication.chattyuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChattyGroupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('date_joined', models.BigIntegerField()),
                ('chatty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.chattyuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.chattygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Acquaintance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(blank=True, max_length=50)),
                ('chatty_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatty_user_aq', to='Authentication.chattyuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.chattygroup')),
                ('user_acquaintance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquaintance', to='Authentication.chattyuser')),
            ],
        ),
    ]
