# Generated by Django 3.2.4 on 2021-06-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_remove_acquaintance_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquaintance',
            name='user_acquaintance',
        ),
    ]
