# Generated by Django 3.2.4 on 2021-06-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_alter_chattyuser_number'),
        ('Chat', '0003_remove_acquaintance_user_acquaintance'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquaintance',
            name='user_acquaintance',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='acquaintance', to='Authentication.chattyuser'),
            preserve_default=False,
        ),
    ]
