# Generated by Django 3.2.4 on 2021-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_acquaintance_user_acquaintance'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattyusernotification',
            name='detail',
            field=models.CharField(default='Group', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
