# Generated by Django 3.2.4 on 2021-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattyuser',
            name='acquaintance',
            field=models.ManyToManyField(to='Authentication.ChattyUser'),
        ),
        migrations.AlterField(
            model_name='chattyuser',
            name='biography',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chattyuser',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chattyuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
