# Generated by Django 3.2.4 on 2021-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20210617_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattyuser',
            name='token',
            field=models.CharField(default='s', max_length=100),
            preserve_default=False,
        ),
    ]
