# Generated by Django 3.2.4 on 2021-06-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_chattyuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattyuser',
            name='acquaintance',
        ),
        migrations.AddField(
            model_name='chattyuser',
            name='email',
            field=models.EmailField(default='d', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chattyuser',
            name='username',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chattyuser',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
