# Generated by Django 3.2.4 on 2021-06-19 08:43

import Authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_chattyuser_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattyuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Authentication.models.image_pathname),
        ),
    ]
