# Generated by Django 3.2.4 on 2021-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_chattyuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattyuser',
            name='last_seen',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
