# Generated by Django 3.2.4 on 2021-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_chattyuser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattyuser',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
